### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by SchSeba**
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/bridge-marker/5)

### CODE REVIEW

**Comment by phoracek** [comment]
@SchSeba @mmirecki https://github.com/kubevirt/bridge-marker/pull/2 pushes to quay on merge too (or it should). Please use only one of them. I would vote to push using travis, since we do it in all the other networking repositories.

**Comment by SchSeba** [comment]
@phoracek can we merge it?

**Comment by phoracek** [comment]
@SchSeba sure, acked from my side.

**Comment by phoracek** [comment]
ci test please

**Comment by SchSeba** [comment]
I can try to rebase

**Comment by SchSeba** [comment]
ci test please

**Pull request merged**
