### PR TITLE
Add more details and examples for platform configuration

### PR DESCRIPTION
**Pull request by ashokpariya0**
Enhanced the comments to provide more clarity on how to configure platforms for multi-platform builds.

**What this PR does / why we need it**:
Enhanced comments to provide more details on setting platforms for multi-platform image builds.
Added examples for configuring PLATFORMS and using the PLATFORM_LIST variable.
Clarified the default behavior (builds based on the host architecture).
Provided options for setting specific platforms or using all to include all supported platforms.

**Special notes for your reviewer**:
For clarity, the main reason is that we need a new release following the changes made to the publish job in PR:
https://github.com/kubevirt/project-infra/pull/3819.

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by ashokpariya0** [comment]
cc @oshoval

**Review by oshoval — APPROVED** [review]
Thanks

For visibility, the real reason is that we need a new release now that the publish job was changed.
We would also need a tag afterwards please

**Comment by ashokpariya0** [comment]
cc @phoracek

**Review by phoracek — APPROVED** [review]

**Comment by phoracek** [comment]
Thanks for the contribution. I have released https://github.com/kubevirt/bridge-marker/releases/tag/0.12.0

**Comment by ashokpariya0** [comment]
> Thanks for the contribution. I have released https://github.com/kubevirt/bridge-marker/releases/tag/0.12.0
>
@phoracek Thank you so much! I can now see that the multi-platform supported images are available at [Quay](https://quay.io/repository/kubevirt/bridge-marker?tab=tags&tag=latest). I also did a quick sanity check on s390x, and everything looks good to me.
@oshoval I really appreciate all your help, thorough reviews, and attention to detail. Your effort has been invaluable, and I’m grateful for your support.

**Pull request merged**
