### PR TITLE
Bump KUBEVIRT_PROVIDER to k8-1.19

### PR DESCRIPTION
**Pull request by RamLavi**
This PR introduces several infra change where the final goal is to add KUBEVIRT_PROVIDER k8-1.19

- **cluster, Change kubevirtci.sh to cluster.sh**
Currently the kubevirtci.sh uses an internal
var KUBEVIRTCI_PATH which collides with _kubevirtci
scripts.
In order to avoid this naming collision, we
change the name of the script to cluster.sh,
and it's variables and functions accordingly.

- **provider, bump provider to k8s-1.19**

- **cluster scripts, Fix cluster.sh to remove _kubevirtci folder**
Currently, when kubevirtci tag version is changed, we get
an error when accessing kubevirtci::install.
Added a fix that will clean up the old _kubevirtci folder

- **bump rbac.authorization.k8s.io to v1**
Currently make cluster sync is stuck since we get
a wraning that current rbac.authorization.k8s.io/v1veta1
will soon be deprecated.
Bumped rbac.authorization.k8s.io to v1 in manifests.

- **cluster-sync, fix cluster sync wait for daemonset to stablize**
Currently sync.sh script may not really wait for daemonset
to be ready, as the desired_nodes is initially 0, making
the wait obsolete.
Added a condition to deny desired_nodes=0 scenario, and
also added small sleep to give the daemonset some time
to stabilizes.

### CODE REVIEW

**Comment by RamLavi** [comment]
@phoracek could you take a look?

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
